WIP: ack packets for better delivery confirmation
attempt to be more robust; if packets get lost because of a crash, allow for redelivery. pika is buggy when binding:

2011-11-02 23:00:39,336 ERROR [MainThread] Listener -- error binding
Traceback (most recent call last):
  File "./db_logging_receiver.py", line 62, in __init__
    routing_key = rk)
  File "build/bdist.macosx-10.7-intel/egg/pika/spec.py", line 2458, in queue_bind
    [Queue.BindOk])
  File "build/bdist.macosx-10.7-intel/egg/pika/adapters/blocking_connection.py", line 205, in rpc
    self._on_rpc_complete)
TypeError: 'NoneType' object is not iterable

Going to switch to async to see if the problem goes away.