Revert "switch serialization to JSON for more public data"
This reverts commit a1bf94fb3e6c796794ac93fe4da120217d804e06.

Traceback (most recent call last):
  File "/home/blalor/xbee_dispatcher/consumer.py", line 565, in __on_receive_packet
    except:
  File "./power_consumer.py", line 38, in handle_packet
    self.publish_sensor_data('electric_meter', sensor_frame)
  File "/home/blalor/xbee_dispatcher/consumer.py", line 586, in publish_sensor_data
    )
  File "/usr/lib/python2.6/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.6/json/encoder.py", line 367, in encode
    chunks = list(self.iterencode(o))
  File "/usr/lib/python2.6/json/encoder.py", line 309, in _iterencode
    for chunk in self._iterencode_dict(o, markers):
  File "/usr/lib/python2.6/json/encoder.py", line 275, in _iterencode_dict
    for chunk in self._iterencode(value, markers):
  File "/usr/lib/python2.6/json/encoder.py", line 317, in _iterencode
    for chunk in self._iterencode_default(o, markers):
  File "/usr/lib/python2.6/json/encoder.py", line 323, in _iterencode_default
    newobj = self.default(o)
  File "/usr/lib/python2.6/json/encoder.py", line 344, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2011, 11, 6, 18, 21, 57, 474466) is not JSON serializable